server:
  port: 9100

spring:
  application:
    name: online-taxi-zuul

eureka:
  client:
    service-url:
      defaultZone: http://eureka-7900:7900/eureka/
  instance:
    hostname: localhost
    instance-id: online-taxi-zuul
zuul:
  sensitive-headers:

## 方便 过滤器的查看，http://localhost:9100/actuator/filters
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      enabled: true
    routes:
      enabled: true
